config/routes.rb
Scottwebsite::Application.routes.draw do
  devise_for :users

    root 'beers#index'
	resources :beers
	resources :comments
	resources :votes
	get '/contact', to: 'static#contact'
	get '/about', to: 'static#about'
	get '/donate', to: 'static#donate'
	
end

app/models/beer.rb
class Beer < ActiveRecord::Base
belongs_to :user
has_many :votes
has_many :comments



BEER_TYPES = ["category 1", "category 2", "category 3","category 4 ","category 5"]

BEER_RATING = ["1", "2", "3","4 ","5"]




#commenting out due to datatables gem providing search
# def self.search(query)
# # where(:title, query) -> This would return an exact match of the query
# where("rec_description like ? OR rec_type like ? OR link like ?", "%#{query}%","%#{query}%","%#{query}%") 
# 
# end



end

app/models/comment.rb
class Comment < ActiveRecord::Base
  #attr_accessible :message, :user_id, :recommendation_id
  #has_one :user
  belongs_to :user
  belongs_to :beer
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :votes
  has_many :comments

end

app/models/vote.rb
class Vote < ActiveRecord::Base
belongs_to :user
belongs_to :beer
validates :user_id, :uniqueness => { :scope => :beer_id }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
before_filter :authenticate_user!, :except => [:index, :show] 
helper_method :sort_column, :sort_direction
 
def show
@beers = Beer.find(params[:id])
@comment= Comment.new
end


def index
  respond_to do |format|
    format.html
    format.json { render json: BeersDatatable.new(view_context) }
  end
end


def new
 @beer=Beer.new
end

def create
 @beer=Beer.new(allowed_params)
 @beer.save
end

#only let this method be accessible within this specific class
private
def allowed_params
  params.require(:beer).permit(:title, :category, :rating, :country, :state_or_province)
end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_filter :authenticate_user!, :except => [:index, :show]

  
  def create
    @comment = current_user.comments.create(allowed_params)
  	redirect_to :back
  end
  
  
  def new
    @comment=Comment.new
  end


private
def allowed_params
  params.require(:comment).permit(:message, :user_id, :beer_id)
end


end

app/controllers/static_controller.rb
class StaticController < ApplicationController
#dont authenticate user before letting them see these pages
skip_before_action :authorize


def index
end


end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
before_filter :authenticate_user!

def create
@votes = Vote.where(:beer_id => params[:vote][:beer_id], :user_id => current_user.id).first
if @votes
  @votes.up = params[:vote][:up]
  @votes.save
else
  @votes = current_user.votes.create(allowed_params)
end
redirect_to :back

end


private 

def allowed_params
  params.require(:vote).permit(:up, :user_id, :beer_id)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/beers/create.html.erb
beer created

app/views/beers/index.html.erb
<h4>All your recommendations are below</h4>
<%= link_to "Add a beer", new_beer_path %>

<table id="beers" class="display" data-source="<%= beers_url(format: "json") %>">
  <thead>
<tr>
      <th>Beer Name</th>
      <th>Rating</th>
      <th>Country</th>
      <th>State or Province</th>
      <th>Votes</th>
      <th>Click to Comment</th>
      <th> Up/downvote </th>

    </tr>
  </thead>
  <tbody>
  </tbody>
</table>

app/views/beers/new.html.erb
<h4>Add a new Beer</h4>


<%= form_for @beer, url: {action: "create"} do |f| %>
    <% if @beer.errors.any? %>
    <div id="error_explanation">
    <h2><%= pluralize(@beer.errors.count, "error") %> prohibited this beer from being saved:</h2>
	<% end %> 
	  
  <div><%= f.label "Name of Beer" %><br />
  <%= f.text_field :title %></div>	  
	  
  <div><%= f.label "Beer Category"%><br />
  <%= f.select(:category, Beer::BEER_TYPES) %></div>
  
  <div><%= f.label "Beer Rating"%><br />
  <%= f.select(:rating, Beer::BEER_RATING) %></div>

  <div> <%= f.submit "Add Beer" %></div>
<% end %>

app/views/beers/show.html.erb
<h4>Beer!</h4>
<%= link_to "Add another beer", new_beer_path %>



<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
   
    <%= f.text_area :message, :placeholder => "Add a comment" %>
    <%= f.hidden_field :beer_id, :value => @beers.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<h2>Comments:<h2>
<div>
  <% @beers.comments.joins(:user).each do |comment| %>
    <p><%= comment.message %> 
    	Posted at <%= comment.created_at.strftime("%Y-%m-%d %H:%M:%S") %>
    	by <%= comment.user.email %>
    </p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Scottwebsite" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>


    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" <%= link_to "Scott's Beer Tasting", "http://scottsbeeradventures.herokuapp.com/" %></a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "About", "/about" %></li>
              <li><%= link_to "Contact", "/contact"  %></li>
              <li><%= link_to "Donation Information", "/donate"  %></li>
              <li> <%=link_to "Log-in", new_user_session_path %> </li> 
			  <li> <%=link_to "Register", new_user_registration_path %> </li> 
            <% if user_signed_in? %>  
           		<li> <%= menu_text "Signed in as #{current_user.email} " %> </li>
            	<li>  <%= link_to "Log-out", destroy_user_session_path, method: :delete %> </li> 
            <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>


        <div class="span8">
          <%= bootstrap_flash %>
          <%= yield %>
          
    <img src="/assets/scott.png" alt="scott" > 
          
        </div>
      </div><!--/row-->

    </div> <!-- /container -->


      <footer>
        <p>&copy; A Scott Holbrook Production</p>
      </footer>


  </body>
</html>

app/views/layouts/fixed.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Scottwebsite" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Scottwebsite</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          <div class="span3">
            <div class="well sidebar-nav">
              <h3>Sidebar</h3>
              <ul class="nav nav-list">
                <li class="nav-header">Sidebar</li>
                <li><%= link_to "Link1", "/path1"  %></li>
                <li><%= link_to "Link2", "/path2"  %></li>
                <li><%= link_to "Link3", "/path3"  %></li>
              </ul>
            </div><!--/.well -->
          </div><!--/span-->
        </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>